-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtrSn1bNvDFdbRANM
mLqWppmtU2LWvzlYmRxvafMkl8SgCgYIKoZIzj0DAQehRANCAAQdaBfiyTVZO7+D
gnLFOEEOe08FhOvs58pz+ndyuOdsoUGoFuS7mQdciN3sw5bIa8XkGedrbNjTzn6p
icgLX5cY
-----END PRIVATE KEY-----