platform :ios, '13.0'

target 'InventoryApp' do
  use_frameworks!
  
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'


end
